import re
from pathlib import Path
from typing import List, Tuple
from .models import Project, Blueprint

GENERATED_BASE_DIR = Path(__file__).resolve().parent.parent.parent / "generated_projects"


def slugify(text: str) -> str:
    s = text.lower().strip()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s_-]+", "-", s)
    return s.strip("-") or "project"


class ProjectScaffolder:
    @classmethod
    def scaffold(cls, project: Project) -> Tuple[str, List[str]]:
        """
        Transforms an approved project blueprint into physical starter files and directories.
        Returns (project_dir_path, list_of_relative_files_created).
        """
        bp: Blueprint = project.blueprint
        if not bp:
            raise ValueError(f"Project '{project.name}' does not have a generated blueprint yet.")

        project_slug = slugify(project.name)
        project_dir = GENERATED_BASE_DIR / project_slug
        project_dir.mkdir(parents=True, exist_ok=True)

        files_created: List[str] = []

        def write_file(rel_path: str, content: str) -> None:
            full_path = project_dir / rel_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            with open(full_path, "w", encoding="utf-8") as f:
                f.write(content.strip() + "\n")
            files_created.append(rel_path)

        # 1. README.md
        readme_content = f"""# {project.name}

> Generated by **ROGERS — AI Project Orchestrator**

## Executive Summary
{bp.summary}

## Technology Stack
- **Frontend**: {bp.tech_stack.frontend}
- **Backend**: {bp.tech_stack.backend}
- **Database**: {bp.tech_stack.database}
- **AI/ML**: {bp.tech_stack.ai}

## Architecture Overview
{bp.architecture.description}

### Core Components
{chr(10).join(f"- {c}" for c in bp.architecture.components)}

## Getting Started

### Prerequisites
- Docker & Docker Compose
- Python 3.11+
- Node.js 18+

### Running with Docker Compose
```bash
docker-compose up -d
```

### Local Development

#### Backend
```bash
cd backend
python -m venv .venv
source .venv/bin/activate  # Or on Windows: .venv\\Scripts\\activate
pip install -r requirements.txt
uvicorn app.main:app --reload --port 8000
```

#### Frontend
```bash
cd frontend
npm install
npm run dev
```

## Development Tasks & Roadmap
{chr(10).join(f"{i+1}. **{t.title}** [{t.priority.upper()}]\n   {t.description}" for i, t in enumerate(bp.development_tasks))}

## Immediate Next Steps
{chr(10).join(f"{i+1}. {s}" for i, s in enumerate(bp.next_steps))}
"""
        write_file("README.md", readme_content)

        # 2. docker-compose.yml
        docker_compose = f"""version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/{project_slug.replace('-', '_')}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB={project_slug.replace('-', '_')}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
"""
        write_file("docker-compose.yml", docker_compose)

        # 3. .env.example
        env_example = f"""# {project.name} Environment Configuration
PORT=8000
HOST=0.0.0.0
DEBUG=True
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/{project_slug.replace('-', '_')}
REDIS_URL=redis://localhost:6379/0
SECRET_KEY=replace_with_a_secure_secret_key_in_production
"""
        write_file(".env.example", env_example)

        # 4. backend/app/main.py
        backend_main = f'''from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="{project.name} API",
    description="{bp.summary.replace('"', '')}",
    version="0.1.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/api/health")
async def health():
    return {{"status": "healthy", "service": "{project.name}"}}

@app.get("/api/info")
async def info():
    return {{
        "name": "{project.name}",
        "architecture": "{bp.architecture.description.replace('"', '')}"
    }}
'''
        write_file("backend/app/main.py", backend_main)

        # 5. backend/app/models.py
        backend_models = '''from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime

class HealthResponse(BaseModel):
    status: str
    service: str

class ItemBase(BaseModel):
    title: str
    description: Optional[str] = None

class ItemCreate(ItemBase):
    pass

class Item(ItemBase):
    id: str
    created_at: datetime
'''
        write_file("backend/app/models.py", backend_models)

        # 6. backend/requirements.txt
        reqs = """fastapi>=0.110.0
uvicorn[standard]>=0.28.0
pydantic>=2.6.0
python-dotenv>=1.0.0
httpx>=0.27.0
pytest>=8.0.0
"""
        write_file("backend/requirements.txt", reqs)

        # 7. backend/Dockerfile
        dockerfile = """FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""
        write_file("backend/Dockerfile", dockerfile)

        # 8. frontend/package.json
        fe_package = f'''{{
  "name": "{project_slug}-client",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "lucide-react": "^0.475.0"
  }},
  "devDependencies": {{
    "@types/react": "^18.3.18",
    "@types/react-dom": "^18.3.5",
    "@vitejs/plugin-react": "^4.3.4",
    "tailwindcss": "^3.4.17",
    "autoprefixer": "^10.4.20",
    "postcss": "^8.5.1",
    "vite": "^6.1.0"
  }}
}}'''
        write_file("frontend/package.json", fe_package)

        # 9. frontend/src/App.jsx
        fe_app = f'''import React, {{ useState, useEffect }} from 'react';

export default function App() {{
  const [info, setInfo] = useState(null);

  useEffect(() => {{
    fetch('/api/info')
      .then(res => res.json())
      .then(data => setInfo(data))
      .catch(() => {{}});
  }}, []);

  return (
    <div style={{{{ minHeight: '100vh', background: '#0f172a', color: '#f8fafc', padding: '2rem', fontFamily: 'sans-serif' }}}}>
      <header style={{{{ maxWidth: '800px', margin: '0 auto', borderBottom: '1px solid #334155', paddingBottom: '1.5rem' }}}}>
        <h1 style={{{{ fontSize: '2rem', fontWeight: 'bold' }}}}>{project.name}</h1>
        <p style={{{{ color: '#94a3b8', marginTop: '0.5rem' }}}}>{bp.summary}</p>
      </header>
      <main style={{{{ maxWidth: '800px', margin: '2rem auto' }}}}>
        <div style={{{{ background: '#1e293b', borderRadius: '0.75rem', padding: '1.5rem', border: '1px solid #334155' }}}}>
          <h2 style={{{{ fontSize: '1.25rem', fontWeight: '600', marginBottom: '1rem' }}}}>System Status</h2>
          <p>Frontend: <strong>Active</strong></p>
          <p>Backend API Connected: <strong>{{info ? 'Yes' : 'Checking...'}}</strong></p>
        </div>
      </main>
    </div>
  );
}}'''
        write_file("frontend/src/App.jsx", fe_app)

        # 10. frontend/index.html
        fe_index = f'''<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{project.name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>'''
        write_file("frontend/index.html", fe_index)

        # 11. frontend/src/main.jsx
        fe_main = '''import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);'''
        write_file("frontend/src/main.jsx", fe_main)

        # 12. docs/ARCHITECTURE.md
        docs_arch = f"""# System Architecture: {project.name}

## Overview
{bp.architecture.description}

## Component Boundaries
{chr(10).join(f"### {c}\n- Core responsibilities and interactions." for c in bp.architecture.components)}

## Technology Stack Rationale
- **Frontend**: {bp.tech_stack.frontend}
- **Backend**: {bp.tech_stack.backend}
- **Database**: {bp.tech_stack.database}
- **AI/ML**: {bp.tech_stack.ai}
"""
        write_file("docs/ARCHITECTURE.md", docs_arch)

        # 13. docs/REQUIREMENTS.md
        docs_reqs = f"""# Requirements Specification: {project.name}

## Functional Requirements
{chr(10).join(f"- [ ] {r}" for r in bp.requirements)}

## Non-Functional Requirements
- Security: Role-based access control, input sanitization, JWT authorization.
- Performance: Sub-second API response times for standard queries.
- Observability: Structured logging, health check probes, telemetry metrics.
"""
        write_file("docs/REQUIREMENTS.md", docs_reqs)

        # 14. docs/BLUEPRINT.md
        docs_bp = f"""# Engineering Blueprint: {project.name}

## Summary
{bp.summary}

## Development Roadmap
{chr(10).join(f"### Phase {i+1}: {t.title} ({t.priority.upper()})\n{t.description}\n" for i, t in enumerate(bp.development_tasks))}

## Next Steps
{chr(10).join(f"{i+1}. {s}" for i, s in enumerate(bp.next_steps))}
"""
        write_file("docs/BLUEPRINT.md", docs_bp)

        return str(project_dir.resolve()), files_created
